"""Plugin system for report types.

Each report type (Contact Center, Turnos, Laboratorio, etc.) is a plugin
that lives in ``app/plugins/<name>/`` and registers itself by subclassing
:class:`ReportPlugin`.

The :class:`PluginRegistry` discovers and loads every plugin package at
startup so the UI can present them in a dropdown.
"""

from __future__ import annotations

import importlib
import pkgutil
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd


# ---------------------------------------------------------------------------
# Data contracts returned by plugins
# ---------------------------------------------------------------------------

@dataclass
class ColumnSpec:
    """Describes one expected column in the source CSV."""

    name: str
    dtype: str = "object"          # pandas dtype string
    required: bool = True
    description: str = ""


@dataclass
class DataSchema:
    """Defines the expected shape of the raw data for a plugin."""

    columns: list[ColumnSpec]
    separator: str = ";"
    decimal: str = ","
    encoding: str = "utf-8"
    date_column: str = "LOGDATE"
    has_total_row: bool = True      # Tecnovoz CSVs end with a "Total" row


@dataclass
class KPIDefinition:
    """One KPI to be computed by the KPI engine."""

    id: str                         # e.g. "recibidas"
    label: str                      # e.g. "Recibidas"
    unit: str = ""                  # e.g. "%", "HH:MM:SS", ""
    source_column: str = ""         # CSV column to aggregate
    aggregation: str = "sum"        # sum | mean | custom
    format_str: str = "{:,.0f}"     # Python format string
    description: str = ""


@dataclass
class ChartDefinition:
    """One chart to be generated by the chart engine."""

    id: str                         # e.g. "daily_distribution"
    chart_type: str                 # "bar_line" | "horizontal_bar" | "donut" | "grouped_bar"
    title: str = ""
    x_column: str = ""
    y_columns: list[str] = field(default_factory=list)
    line_column: str = ""           # for combo bar+line charts
    description: str = ""
    kwargs: dict[str, Any] = field(default_factory=dict)


@dataclass
class PromptConfig:
    """Prompt templates for the AI engine."""

    executive_summary: str = ""
    conclusions: str = ""
    recommendations: str = ""
    anomaly_detection: str = ""


# ---------------------------------------------------------------------------
# Abstract plugin base
# ---------------------------------------------------------------------------

class ReportPlugin(ABC):
    """Base class every report plugin must subclass.

    Subclasses register automatically when their module is imported.
    """

    # Metadata — set by subclass
    name: str = ""                  # Internal ID  (e.g. "contact_center")
    display_name: str = ""          # UI label     (e.g. "Productividad del Contact Center")
    description: str = ""

    @abstractmethod
    def get_schema(self) -> DataSchema:
        """Return the expected data schema for this report type."""

    @abstractmethod
    def get_kpis(self) -> list[KPIDefinition]:
        """Return the list of KPIs to compute."""

    @abstractmethod
    def get_charts(self) -> list[ChartDefinition]:
        """Return the list of charts to generate."""

    @abstractmethod
    def get_prompts(self) -> PromptConfig:
        """Return prompt templates for AI-generated text."""

    @abstractmethod
    def get_template_path(self) -> Path | None:
        """Return the path to the PPTX/DOCX template, or None."""

    def get_campaign_mapping(self) -> dict[str, list[str]]:
        """Return a mapping of campaign name → list of skill CSV filenames.

        Override in the plugin to define how individual skill CSVs are
        grouped into campaigns.  The default returns an empty dict
        (meaning "each file is its own campaign").
        """
        return {}

    def post_process(self, data: pd.DataFrame) -> pd.DataFrame:
        """Optional hook to transform data after loading and before KPIs."""
        return data


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

class PluginRegistry:
    """Discovers and holds all available report plugins."""

    def __init__(self) -> None:
        self._plugins: dict[str, ReportPlugin] = {}

    # -- public API --------------------------------------------------------

    def register(self, plugin: ReportPlugin) -> None:
        """Register a plugin instance."""
        if not plugin.name:
            raise ValueError(f"Plugin {plugin.__class__.__name__} has no 'name'.")
        self._plugins[plugin.name] = plugin

    def get(self, name: str) -> ReportPlugin:
        """Retrieve a plugin by its internal name."""
        if name not in self._plugins:
            available = ", ".join(self._plugins) or "(none)"
            raise KeyError(f"Plugin '{name}' not found. Available: {available}")
        return self._plugins[name]

    def list_plugins(self) -> list[ReportPlugin]:
        """Return all registered plugins."""
        return list(self._plugins.values())

    def discover(self, package_path: str = "app.plugins") -> None:
        """Auto-discover plugins under *package_path*.

        Each sub-package must have a ``plugin.py`` that instantiates
        and registers a :class:`ReportPlugin` subclass.
        """
        try:
            package = importlib.import_module(package_path)
        except ModuleNotFoundError:
            return

        if not hasattr(package, "__path__"):
            return

        for _importer, modname, _ispkg in pkgutil.iter_modules(package.__path__):
            try:
                module = importlib.import_module(f"{package_path}.{modname}.plugin")
                # Convention: the module exposes ``plugin_instance``
                if hasattr(module, "plugin_instance"):
                    self.register(module.plugin_instance)
            except Exception as exc:  # noqa: BLE001
                print(f"[PluginRegistry] Failed to load '{modname}': {exc}")


# Module-level singleton
registry = PluginRegistry()
